package com.hedvig.underwriter.graphql.type

enum class ContractAgreementType {
    SE_HOUSE,
    SE_APARTMENT_BRF,
    SE_APARTMENT_RENT,
    SE_APARTMENT_STUDENT_BRF,
    SE_APARTMENT_STUDENT_RENT,
    NO_HOME_CONTENT_OWN,
    NO_HOME_CONTENT_RENT,
    NO_HOME_CONTENT_YOUTH_OWN,
    NO_HOME_CONTENT_YOUTH_RENT,
    NO_TRAVEL,
    NO_TRAVEL_YOUTH,
    DK_HOME_CONTENT_OWN,
    DK_HOME_CONTENT_RENT,
    DK_HOME_CONTENT_STUDENT_OWN,
    DK_HOME_CONTENT_STUDENT_RENT
}
