package com.hedvig.underwriter.service.guidelines

object BreachedGuidelinesCodes {
    const val INVALID_SSN = "INVALID_SSN"
    const val INVALID_SSN_LENGTH = "INVALID_SSN_LENGTH"
    const val SSN_DOES_NOT_MATCH_BIRTH_DATE = "SSN_DOES_NOT_MATCH_BIRTH_DATE"
    const val UNDERAGE = "UNDERAGE"
    const val DEBT_CHECK = "DEBT_CHECK"

    const val NEGATIVE_NUMBER_OF_CO_INSURED = "NEGATIVE_NUMBER_OF_CO_INSURED"
    const val TOO_SMALL_LIVING_SPACE = "TOO_SMALL_LIVING_SPACE"
    const val TOO_HIGH_NUMBER_OF_CO_INSURED = "TOO_HIGH_NUMBER_OF_CO_INSURED"
    const val TOO_MUCH_LIVING_SPACE = "TOO_MUCH_LIVING_SPACE"
    const val YOUTH_TOO_HIGH_NUMBER_OF_CO_INSURED = "YOUTH_TOO_HIGH_NUMBER_OF_CO_INSURED"

    const val TOO_SMALL_NUMBER_OF_HOUSE_HOLD_SIZE = "TOO_SMALL_NUMBER_OF_HOUSE_HOLD_SIZE"
    const val TOO_HIGH_NUMBER_OF_HOUSE_HOLD_SIZE = "TOO_HIGH_NUMBER_OF_HOUSE_HOLD_SIZE"

    const val TOO_EARLY_YEAR_OF_CONSTRUCTION = "TOO_EARLY_YEAR_OF_CONSTRUCTION"
    const val TOO_MANY_BATHROOMS = "TOO_MANY_BATHROOMS"
    const val TOO_MANY_EXTRA_BUILDINGS = "TOO_MANY_EXTRA_BUILDINGS"
    const val TOO_BIG_EXTRA_BUILDING_SIZE = "TOO_BIG_EXTRA_BUILDING_SIZE"
    const val TOO_SMALL_EXTRA_BUILDING_SIZE = "TOO_SMALL_EXTRA_BUILDING_SIZE"

    const val STUDENT_TOO_BIG_HOUSE_HOLD_SIZE = "STUDENT_TOO_BIG_HOUSE_HOLD_SIZE"
    const val STUDENT_TOO_MUCH_LIVING_SPACE = "STUDENT_TOO_MUCH_LIVING_SPACE"
    const val STUDENT_OVERAGE = "STUDENT_OVERAGE"

    const val YOUTH_TOO_MUCH_LIVING_SPACE = "YOUTH_TOO_MUCH_LIVING_SPACE"
    const val YOUTH_OVERAGE = "YOUTH_OVERAGE"
}
